### ISSUE TITLE
IMAGE_PROCESS_FAILED when sending image

### ISSUE THREAD

**Issue by Radzhab** [justdmitry/NetTelegramBotApi#10]
В общем даже не знаю зачем тут этот метод. Всегда возвращает null. Пробую загрузить картинку в Stream. По любому возвращает 
`{"ok":false,"error_code":400,"description":"Error: IMAGE_PROCESS_FAILED"}.`

```
var data = Translit(city);
            try
            {
               data = "D:\\123";
                var reqAction = new SendChatAction(chat_id, "upload_photo");
                bot.MakeRequestAsync(reqAction).Wait();
                System.Threading.Thread.Sleep(500);
                System.Drawing.Image image = Image.FromFile(string.Format("{0}.png", data));
                using (MemoryStream stream = new MemoryStream())
                {
                    // Save image to stream.
                    image.Save(stream, ImageFormat.Bmp);


                    using (var photoData =Assembly.GetExecutingAssembly().GetManifestResourceStream(string.Format("{0}.png", data)))
                    {
                        var req = new SendPhoto(chat_id, new FileToSend(stream, string.Format(".png", city)))
                        {
                            Caption = "Telegram_logo.png"
                        };
                        var msg = bot.MakeRequestAsync(req).Result;
                        uploadedPhotoId = msg.Photo.Last().FileId;
                    }
                }
            }
```

**Comment by Radzhab** [comment]
Вот в post Запросе данные

```
--bdc6b644-46fc-4c05-a430-9675f3c6a198
Content-Type: text/plain; charset=utf-8
Content-Disposition: form-data; name=caption

.png
--bdc6b644-46fc-4c05-a430-9675f3c6a198
Content-Type: text/plain; charset=utf-8
Content-Disposition: form-data; name=chat_id

10902074
--bdc6b644-46fc-4c05-a430-9675f3c6a198
Content-Disposition: form-data; name=photo; filename=.png; filename*=utf-8''.png
```

**Comment by justdmitry** [comment]
Метод кажется не при чем, если stream==null то упало бы раньше. Тут уже серверу телеграмовскому что-то не нравится.

1) `new FileToSend(stream, string.Format(".png", city))` - разве не должно быть "{0}.png" ?
2) сам файл точно "нормальная картинка"? вдруг там не изображение...

до кучи - обнови библиотеку до 3.4 (или даже 3.5) - там было исправление #5 про utf-8 имена файлов

**Comment by Radzhab** [comment]
Имена на транслите. по поводу картинки. Вот оно) Поправил string.Format выше
![1_white ru](https://cloud.githubusercontent.com/assets/2556411/9294441/41a381fe-4456-11e5-8934-ebc1ca12f568.png)

**Comment by Radzhab** [comment]
Посмотрел запрос. 

```
РјР°С…Р°С‡РєР°Р»Р°.png
--e51baa44-3e49-4256-89f5-585c08e0b6ff
Content-Type: text/plain; charset=utf-8
Content-Disposition: form-data; name=chat_id
```

Хм. Откуда там UTF-8 когда название файла у меня на инглише? Либы обновил

Content-Disposition: form-data; name=photo; filename="=?utf-8?B?0LzQsNGF0LDRh9C60LDQu9CwLnBuZw==?="; filename*=utf-8''%D0%BC%D0%B0%D1%85%D0%B0%D1%87%D0%BA%D0%B0%D0%BB%D0%B0.png

**Comment by justdmitry** [comment]
Судя по тому что ты в string.format отдаешь City - я вполне ожидал там русский текст. Имя файла без имени (.png) еще могло быть "плохим" для сервера, а нормальное имя должно кушаться. Даже русское имя файла норм, проверяется командой `/docutf8` в тестовом проекте (про эту багу и был тикет #5).

Но вот только про версию обновленную я очень не уверен... Как раз вчера исправляя #5 я вручную начал формировать `Content-Disposition`, и там теперь нет `filename*` (который не понимает сервер телеграм), только `filename`...

Конкретно по твоему коду есть еще идея. Ты приводил примеры полного запроса или отрезал что-то? Там подозрительно нет самого содержимого файла. Попробуй сделать `stream.Position=0` после `Image.Save(...)` - это "сдвинет" позицию на начало, может в этом дело.

**Comment by Radzhab** [comment]
Аналогичная ситуация

```
public static void SendWeather(long chat_id,string city)
        {
            var data = Translit(city);
            WebClient webClient = new WebClient();
            try
            {
                webClient.DownloadFile(
                    "http://info.weather.yandex.net/" + data + "/2_white.ru.png?domain=ru",
                    string.Format("{0}.png", data));
                var reqAction = new SendChatAction(chat_id, "upload_photo");
                bot.MakeRequestAsync(reqAction).Wait();

                System.Threading.Thread.Sleep(500);


                System.Drawing.Image image = Image.FromFile(string.Format("{0}.png", data));
                using (MemoryStream stream = new MemoryStream())
                {
                    // Save image to stream.
                    image.Save(stream, ImageFormat.Bmp);
                    stream.Position = 0;

                    using (var photoData =Assembly.GetExecutingAssembly().GetManifestResourceStream(string.Format("{0}.png", data)))
                    {
                        var req = new SendPhoto(chat_id, new FileToSend(stream, string.Format("{0}.png", city)))
                        {
                            Caption = string.Format("{0}.png", city)
                        };
                        var msg = bot.MakeRequestAsync(req).Result;
                        uploadedPhotoId = msg.Photo.Last().FileId;
                    }
                }
            }
            catch (Exception)
            {
                bot.MakeRequestAsync(new SendMessage(chat_id,
                    "Город не найден. Проверь правильность введенного текста!"));

            }
        }
```

![http analyzer v7](https://cloud.githubusercontent.com/assets/2556411/9295149/894c72ac-446c-11e5-911b-f7bbca10ecef.jpg)
![http analyzer v72](https://cloud.githubusercontent.com/assets/2556411/9295155/9a24a964-446c-11e5-8a0a-7347c54e28d5.jpg)

**Comment by justdmitry** [comment]
1) ну вопрос с названием файла на кириллице решен:

```
var data = Translit(city);
...
new FileToSend(stream, string.Format("{0}.png", city))
```

не `city` а `data` во втором случае надо.

2) как только сделал Position=0 - сразу пошли данные и ошибка поменялась, значит проблема была в неправильном "начальном позиционировании" в стриме.

3) Запусти пример и дай боту команду `/docutf8` - что будет в трафике? У меня вот такой запрос:

```
POST https://api.telegram.org/bot....../sendDocument HTTP/1.1
Content-Type: multipart/form-data; boundary="07be7a36-256d-4395-9850-354e906eb39e"
Host: api.telegram.org
Content-Length: 499
Expect: 100-continue

--07be7a36-256d-4395-9850-354e906eb39e
Content-Type: text/plain; charset=utf-8
Content-Disposition: form-data; name=chat_id

24807507
--07be7a36-256d-4395-9850-354e906eb39e
Content-Disposition: form-data; name=document; filename="Пример UTF8 filename.txt"

Eng:
This is sample file with non-latin name (validating issue #5)

Rus:
Это пример файла с кириллицей в названии (проверяем issue #5)
--07be7a36-256d-4395-9850-354e906eb39e--
```

Обрати внимание на `filename` - он один и сразу в utf-8, без дополнительного кодирования. Аналогично и с картинкой (`/photo`), даже если я в Programs.cs в строке 83 меняю имя на русское (`new FileToSend(photoData, "Лого Телеграм.png")`)

**Comment by Radzhab** [comment]
пардон за такую глупейшую опечатку)) ппц одним словом. Попутал city и data. Вся трабла была в этом

**Comment by Radzhab** [comment]
--22b8b851-80f0-4679-81bc-ad0e74823b42
Content-Type: text/plain; charset=utf-8
Content-Disposition: form-data; name=caption

makhachkala.png
--22b8b851-80f0-4679-81bc-ad0e74823b42
Content-Type: text/plain; charset=utf-8
Content-Disposition: form-data; name=chat_id

10902074
--22b8b851-80f0-4679-81bc-ad0e74823b42
Content-Disposition: form-data; name=photo; filename=makhachkala.png; filename*=utf-8''makhachkala.png

**Comment by justdmitry** [comment]
Меня все же не оставляет вопрос с filename*
Этого НЕ должно быть в последней версии (3.5.50816)! Проверь плиз версию и дай боту команду /docutf8 - что будет?

**Comment by Radzhab** [comment]
![d5a50d391e](https://cloud.githubusercontent.com/assets/2556411/9295560/6cd61c0a-447a-11e5-8c80-2f72411c0fff.jpg)

```
--ac94eb5f-1633-4d61-9c53-88f4e72cdd4d
Content-Type: text/plain; charset=utf-8
Content-Disposition: form-data; name=chat_id

10902074
--ac94eb5f-1633-4d61-9c53-88f4e72cdd4d
Content-Disposition: form-data; name=document; filename="=?utf-8?B?0J/RgNC40LzQtdGAIFVURjggZmlsZW5hbWUudHh0?="; filename*=utf-8''%D0%9F%D1%80%D0%B8%D0%BC%D0%B5%D1%80%20UTF8%20filename.txt


--ac94eb5f-1633-4d61-9c53-88f4e72cdd4d--
```

``````
var reqAction = new SendChatAction(chatId, "upload_document");
            bot.MakeRequestAsync(reqAction).Wait();
            System.Threading.Thread.Sleep(500);
            using (var docData = Assembly.GetExecutingAssembly().GetManifestResourceStream("TelegramBotDemo.Пример UTF8 filename.txt"))
            {
                using (FileStream fileStream = File.OpenRead("Пример UTF8 filename.txt"))
                {
                    MemoryStream memStream = new MemoryStream();
                    memStream.SetLength(fileStream.Length);
                    fileStream.Read(memStream.GetBuffer(), 0, (int)fileStream.Length);

                var req = new SendDocument(chatId, new FileToSend(fileStream, "Пример UTF8 filename.txt"));
                var msg = bot.MakeRequestAsync(req).Result;
                    var uploadedDocumentId = msg.Document.FileId;
                }
            }```
``````

**Comment by justdmitry** [comment]
Нет, не переделывать функцию под файл из примера, а запустить прямо пример.
У меня файл успешно отправляется, никаких ошибок.

**Comment by Radzhab** [comment]
Запустил. Вроде гут. Но файл не отправился. Я вот никак не пойму. `Assembly.GetExecutingAssembly().GetManifestResourceStream("TelegramBotDemo.Пример UTF8 filename.txt"))`
Вот этот кусок кода за что отвечает)?

**Comment by justdmitry** [comment]
Этот кусок отвечает за доставание файла из самого exe-шника, куда он был скомпилирован как ресурс. Чтобы не тащить рядом пачку файлов помимо exe.
