### ISSUE TITLE
Error while sending big documents

### ISSUE THREAD

**Issue by hanigamini** [justdmitry/NetTelegramBotApi#11]
Hi,
When i want to send document in line var msg = bot.MakeRequestAsync(req).Result; i have error : 
One or more errors occurred. (How to see the original error?)
my file is pdf and size is 1.7 mb !!!

this is my code , it happens with file 1.7 mb only !!! for 500 k is ok ! please help me
using (var docData = File.OpenRead(FilePath))
{

var req = new SendDocument(update.Message.Chat.Id, new FileToSend(docData, Path.GetFileName(FilePath)));
var msg = bot.MakeRequestAsync(req).Result;
uploadedDocumentId = msg.Document.FileId;
}

**Comment by hanigamini** [comment]
this is my code , it happens with file 1.7 mb  only !!! for 500 k is ok ! please help me
using (var docData = File.OpenRead(FilePath))
                                    {                                       
                                        var req = new SendDocument(update.Message.Chat.Id, new FileToSend(docData, Path.GetFileName(FilePath)));
                                        var msg = bot.MakeRequestAsync(req).Result;
                                        uploadedDocumentId = msg.Document.FileId;
                                    }

**Comment by justdmitry** [comment]
I tested with large files - everything works. I pushed new branch `issue-11` with commands `/pdfsmall` (sends 23KB file) and `/pdflarge` (sends 6 MB file) in demo project - check if they work on your computer.

**Comment by hanigamini** [comment]
Thansk you ,
Very strange !!! my code is ok now with visual studio debug ! but run exe not working in server with this file 1.7 mb  !
How to see the original error instead of "One or more errors occurred."?

**Comment by justdmitry** [comment]
This library does not hide any exceptions, so just look into exception you are receiving - AggregateException as I see - it must contain more details from NET internal code.

**Comment by hanigamini** [comment]
Thanks for your response
i test your code (branch issue-11) with your pdf 6mb ( Sample PDF big.pdf ) and pdf with size 15 mb and i see this error :
An exception of type 'System.AggregateException' occurred in mscorlib.dll but was not handled in user code

Additional information: One or more errors occurred.
System.AggregateException was unhandled by user code
  HResult=-2146233088
  Message=One or more errors occurred.
  Source=mscorlib
  StackTrace:
       at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
       at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
       at System.Threading.Tasks.Task`1.get_Result()
       at TelegramBotDemo.Program.RunBot(String accessToken) in c:\Users\HaniGamini\Desktop\NetTelegramBotApi-issue-11\TelegramBotDemo\Program.cs:line 156
       at TelegramBotDemo.Program.<>c__DisplayClass1.<Main>b__0() in c:\Users\HaniGamini\Desktop\NetTelegramBotApi-issue-11\TelegramBotDemo\Program.cs:line 22
       at System.Threading.Tasks.Task.InnerInvoke()
       at System.Threading.Tasks.Task.Execute()
  InnerException: System.Threading.Tasks.TaskCanceledException
       HResult=-2146233029
       Message=A task was canceled.
       InnerException:

**Comment by justdmitry** [comment]
Are you sure you have enough internet speed to upload such big file to telegram server? How much time (how many seconds) it takes between beginning upload and throwing exception?

**Comment by hanigamini** [comment]
yes i have enough internet speed , 
120 second it take to throwing exception in this line , var msg = bot.MakeRequestAsync(req).Result;
i add this 2 line in MakeRequestAsync method but not solved my problem!
client.DefaultRequestHeaders.ExpectContinue = false;
client.Timeout = TimeSpan.FromMilliseconds(300000);

**Comment by hanigamini** [comment]
Hi,
in method (public async Task<T> MakeRequestAsync<T>(RequestBase<T> request)) 
How can I force my method to run again and again if internet is disconnected?

**Comment by justdmitry** [comment]
Create extension method with logic of your choice (limited/unlimited retries, pause between retries, specific exceptions to catch etc.)

Do you think you problem with uploading big files caused by your unstable (but highspeed) internet connection?

**Comment by hanigamini** [comment]
Yes I guess my problem is lost of packet!
the second problem is that , When the program is running and this line have error (var me = bot.MakeRequestAsync(new GetMe()).Result;) , my app is Does not work and Must be reset again to work.
Can you get a sample code for the run again to answer MakeRequestAsync method?
thanks.

**Comment by justdmitry** [comment]
According to [docs](https://core.telegram.org/bots/api#senddocument), all sent-related methods returns sent `Message` object as result.

So, just check result of MakeRequestAsync like this:

```
var req = new SendDocument(...);
while(true) {
    try {
      var answer = bot.MakeRequestAsync(req);
      if (answer != null) { break; }
    } catch (Exception) {
      // do something like logging, counting, sleping, ...
    }
}
```

**Comment by hanigamini** [comment]
The error is in this line [[using (var response = await client.SendAsync(httpMessage).ConfigureAwait(false))]] in [[public async Task<T> MakeRequestAsync<T>(RequestBase<T> request) ]] method and go to catch , how i return null in catch of thsi method ?

**Comment by hanigamini** [comment]
The error is in this line [[using (var response = await client.SendAsync(httpMessage).ConfigureAwait(false))]] in [[public async Task<T> MakeRequestAsync<T>(RequestBase<T> request) ]] method and go to catch , i return default(T) for null in catch of this method ? 
second time catch throw this error (Error while copying content to a stream.)

**Comment by justdmitry** [comment]
do not catch exception inside library - catch exception outside, when calling `MakeRequestAsync`, and call MakeRequestAsync again

**Comment by hanigamini** [comment]
i use this code but second time i have this error (Error while copying content to a stream.)
  while (true)
                                                    {
                                                        try
                                                        {
                                                            var msg = bot.MakeRequestAsync(req).Result;
                                                            if (msg != null) { break; }
                                                        }
                                                        catch (Exception)
                                                        {
                                                            // do something like logging, counting, sleping, ...
                                                        }
                                                    }

**Comment by justdmitry** [comment]
Try to debug it and find it source and more details. I can't guess.

**Comment by hanigamini** [comment]
I guess my error is for my unstable band width :+1:

**Comment by justdmitry** [comment]
Ok. I dropped branch `issue-11` to minimize repository size.

**Comment by hanigamini** [comment]
Ok , Thanks.
