### ISSUE TITLE
Wait code

### ISSUE THREAD

**Issue by hanigamini** [justdmitry/NetTelegramBotApi#12]
Hi,
What is the reason for use of this code?
bot.MakeRequestAsync(reqAction).Wait();
System.Threading.Thread.Sleep(500);

**Comment by justdmitry** [comment]
Sleep added to simulate 'heavy server load' and allows you to see 'bot is uploading foto...' notification in you Telegram client (as result of `ChatAction` request).

In your real application you should not sleep of course :)

**Comment by hanigamini** [comment]
thanks , I comment this 2 line , 
have any more solution for sending message instead of this line that have wait ?
bot.MakeRequestAsync(new SendMessage(update.Message.Chat.Id, MessageToUser("Not Valid", text))).Wait();

**Comment by justdmitry** [comment]
It's async task and you should `await` it in asynchronous scenarios or `Wait` in synchronous - all like classical .NET async/await.

You can try start several requests in parallel and wait for all of them together, minimizing total time for sending messages to different chats.

**Comment by hanigamini** [comment]
Thank you very much :)
