### ISSUE TITLE
Process image sent by user

### ISSUE THREAD

**Issue by hanigamini** [justdmitry/NetTelegramBotApi#14]
Hi,
How can i work and Analysis the photo that user sended in update.Message.Photo?
i want Analysis photo of user with QR code and return text.
thanks.

**Comment by justdmitry** [comment]
Unfortunately, currently Telegram Bot API does NOT have any method to receive photo/document/file sent to bot by user. Official answer from bot support team was:

> Currently, Bot API doesn't support downloading files

So, we have to wait for next API update[s]...

**Comment by hanigamini** [comment]
Thank you very much :+1:
