### ISSUE TITLE
Using custom keyboard

### ISSUE THREAD

**Issue by hanigamini** [justdmitry/NetTelegramBotApi#15]
Hi,
How do I use the bot keyboard ?

**Comment by justdmitry** [comment]
Use `ReplyMarkup`

**Comment by hanigamini** [comment]
How can i define keyboard element in my bot ?
do you have sample code for ReplyMarkup  in run bot?

**Comment by justdmitry** [comment]
I added new "/help" command to demo project, please check it.

**Comment by hanigamini** [comment]
Thanks you :+1:
