### ISSUE TITLE
Add users.getFullUser method

### ISSUE THREAD

**Issue by Radzhab** [justdmitry/NetTelegramBotApi#16]
) Буду весьма признателен если все функции из `users` будут доступны

**Comment by justdmitry** [comment]
Это где такой метод? Не нахожу его в доках по ботам...

**Comment by Radzhab** [comment]
Пардон) не в те дебри заглянул. https://core.telegram.org/methods

А есть ли вообще такая возможность? Инфу о юзере получить

**Comment by justdmitry** [comment]
Увы. Боты могут только то что им разрешили на https://core.telegram.org/bots/api
