### ISSUE TITLE
Max Text Length

### ISSUE THREAD

**Issue by hanigamini** [justdmitry/NetTelegramBotApi#18]
Hi,
What is max length of text allow telegram to send ? 4096 UTF8 characters ?

**Comment by justdmitry** [comment]
You should ask this to Telegram team, I know nothing about such limitations. Or re-read Bot API manual at https://core.telegram.org/bots/api (I can't find any message maxlength, but check me please).

**Comment by hanigamini** [comment]
Hi,
Bot support reply me :
In a message, a maximum of 4092 characters.

**Comment by justdmitry** [comment]
Thanks!

**Comment by hanigamini** [comment]
Welcome :)
