### ISSUE TITLE
Demo project build error

### ISSUE THREAD

**Issue by vioir** [justdmitry/NetTelegramBotApi#25]
Hi
I've got a problem when i try to build the Demo project in visual studio 2015.
![a0c2f9b0-6a0f-11e5-83f0-a71bb40acf87](https://cloud.githubusercontent.com/assets/13207882/10299308/69fa1764-6bf5-11e5-8457-31f462544264.JPG)

![aad41c7c-6a0f-11e5-9cc8-33ed081c4b3a](https://cloud.githubusercontent.com/assets/13207882/10299305/59c6bfb4-6bf5-11e5-83eb-d5f66e299d02.JPG)

**Comment by justdmitry** [comment]
Did you tried `dnu restore` for every project?

**Comment by vioir** [comment]
yes , but I got error :
![capture](https://cloud.githubusercontent.com/assets/13207882/10422515/56046430-70c8-11e5-9cc8-67be9f14f983.JPG)

**Comment by justdmitry** [comment]
Ooops... Change to beta7, please. It seems to work too.

**Comment by vioir** [comment]
Thank you beta7 was OK.
but still getting same error :

![capture2](https://cloud.githubusercontent.com/assets/13207882/10426065/c5763c96-70e9-11e5-97e0-cf261858c96b.JPG)

**Comment by justdmitry** [comment]
`dnu restore` works per-project - you need run it for main `NextTelegramBotApi` too

**Comment by vioir** [comment]
I ran it in these folders :
NetTelegramBotApi-master , NetTelegramBotApi , TelegramBotDemo , TelegramBotDemo-vNext
where should I run it else ?

**Comment by justdmitry** [comment]
Please show screenshot when running in `NetTelegramBotApi`. This is 'first' project, other depends on it. You should restore dependencies here first.

**Comment by vioir** [comment]
OK
![capture3](https://cloud.githubusercontent.com/assets/13207882/10426377/95c61964-70ec-11e5-8aca-6c20eeab7ea4.JPG)

**Comment by justdmitry** [comment]
Something strange with your VS - `dnu restore` says that all packages are Ok, while VS can't find Newtonsoft.Json and others...

I don't know. Try to rollback to "stable" dnx beta7 - I work with beta7, because all later are not published on nuget and not accessible in Azure.

**Comment by vioir** [comment]
ok thank you I will search for it , and I will share the solution if I figure it out ...

**Comment by justdmitry** [comment]
Projects were updated to RTM. Please open new issue if having problems with "new" build.
