### ISSUE TITLE
send message when user left from group

### ISSUE THREAD

**Issue by nabeghe** [justdmitry/NetTelegramBotApi#28]
i wanna to send message when a user left from group, How do?

**Comment by justdmitry** [comment]
Send message to whom?

To user who left the group? You must have separate chat with this user to send message there. And this chat must be already created (must be already `/start`-ed by that user) - I think it's low possible (why user must have private chat with bot, while it already have group chat with him?)

Send message to chat? Simply send message there. Check for `LeftChatParticipant` property on incoming messages (it must contain user who left the chat) and if it's not null - it will contain user. Then you can send new message with text of your choice to that (or any other) chat.

**Comment by nabeghe** [comment]
Thanks, i wana to send message in group when user left the group or join to group, also send other message in group chat when recive message from group chat. how do this?

**Comment by justdmitry** [comment]
Look into sample project - there are samples how read messages and send messages. No differences send you to chat with one user or to group chat. 

Also use may need to disable 'privacy mode' in your bot settings to see all messages in group chat.
