### ISSUE TITLE
Send audio as voice message

### ISSUE THREAD

**Issue by ghost** [justdmitry/NetTelegramBotApi#29]
i try to get **audio** and then send it as **voice** message.
for this,i download the audio by **GetFile()** and then convert it to .ogg then send it as voice message
by **SendVoice()**
But my robot send nothing !
help  Please.

**Comment by justdmitry** [comment]
Any errors returned?

Are you sure that file converted properly - try to send pre-created .ogg file - what result?

**Comment by ghost** [comment]
thanks.
solved.
i tried to send .ogg file by SendAudio() and its work !
but when i use SendVoice() telegram send nothing and i give no error !

**Comment by justdmitry** [comment]
From https://core.telegram.org/bots/api#sendvoice :

> For this to work, your audio must be in an .ogg file encoded with OPUS (other formats may be sent as Audio or Document). 

Are you sure you have correct .ogg file?
