### ISSUE TITLE
Not an issue, more a request

### ISSUE THREAD

**Issue by Garfius** [justdmitry/NetTelegramBotApi#30]
I really want to develop a server-side interface for a bot using PowerShell.
The only difficulty I am facing is, I cannot load the library NetTelegramBotApi.dll.
It seems the entry point is not declared.

Thanks in advance.

**Comment by justdmitry** [comment]
I never wrote libraries for powershell. Feel free to make pull request.

**Comment by Garfius** [comment]
Just realized the only problem are the dependencies. Can anybody tell me the requiered DDL's ?

Thanks.

**Comment by justdmitry** [comment]
Newtonsoft.Json 7.0.1

**Comment by Garfius** [comment]
Done !
https://github.com/Garfius/powerTelegram

**Comment by justdmitry** [comment]
Cool!
