### ISSUE TITLE
New API

### ISSUE THREAD

**Issue by MPCL5** [justdmitry/NetTelegramBotApi#34]
Hello 
Pplease update your program API 
telegram's API have some new tools but your bot api haven't them

**Comment by justdmitry** [comment]
I have `api_updates` branch for some new stuff, but have no enough time to check it before merging.

**Comment by justdmitry** [comment]
Please take a look at [`v3.9.0-beta3`](https://www.nuget.org/packages/NetTelegramBotApi/3.9.0-beta3) - it contains everything except "Updating messages" and "Inline mode"

**Comment by justdmitry** [comment]
Please reopen if some "new API" is still required (with exact details about missed types/methods).
