### ISSUE TITLE
work keyboard Markup with command

### ISSUE THREAD

**Issue by mohammadmoqadam** [justdmitry/NetTelegramBotApi#35]
hi and thanks for your project
i want use keyboard and set with command .it means when click on keys send command whth \ but dont show in message this message have command .can you help me how i do it?

**Comment by justdmitry** [comment]
Sorry, I don't understand what exactly you want to do.

Please read Telegram Bot API (https://core.telegram.org/bots/api) and find method(s) you need, then you can call them via this lib.
