### ISSUE TITLE
Send bitmap as photo

### ISSUE THREAD

**Issue by shdehnavi** [justdmitry/NetTelegramBotApi#37]
hi

i want to send bitmap variable type as a photo by NetTelegramBotApi:
`Bitmap bmp;`

`using (var photoData = Assembly.GetExecutingAssembly().GetManifestResourceStream("InstagramPuzzleBot.Resources.sample.png"))`
i want to send bitmap contents, what should i write instead of : Assembly.GetExecutingAssembly().GetManifestResourceStream("NetTelegramBotApi.t_logo.png
?

i used this bug i got error:
```
                                Stream mms = new MemoryStream();
                                Bitmap bmp = makePuzzle(address, ID); //function with bitmap return type
                                bmp.Save(mms, System.Drawing.Imaging.ImageFormat.Bmp);

                                var reqAction = new SendChatAction(update.Message.Chat.Id, "upload_photo");
                                bot.MakeRequestAsync(reqAction).Wait();
                                System.Threading.Thread.Sleep(500);
                                using (var photoData = mms)
                                {
                                    var req = new SendPhoto(update.Message.Chat.Id, new FileToSend(photoData, "sample.png"))
                                    {
                                        Caption = "samplephoto"
                                    };
                                    var msg = bot.MakeRequestAsync(req).Result;
                                    SamplePhotoID = msg.Photo.Last().FileId;
                                }
```

**Comment by justdmitry** [comment]
It depends of file location. You can read it with `File.OpenRead` or use `MemoryStream` as a source - there are a lot of choices. You should provide `Stream` to read file from.

About your sample - you forgot to add error text you receive,. BTW I think you should rewind `mms` back to start with `mms.Position = 0` after `bmp.Save`

**Comment by shdehnavi** [comment]
`mms.Position = 0`

solved , thanq
