### ISSUE TITLE
How to send inline keyboard/buttons?

### ISSUE THREAD

**Issue by shdehnavi** [justdmitry/NetTelegramBotApi#39]
hi, i can send replymarkup keyboard but i wanna send inline buttons,
how i can send message with inline keyboard buttons ?

**Comment by justdmitry** [comment]
```
var newMsg = new SendMessage(...) {
    ReplyMarkup = new InlineKeyboardMarkup 
    {
        InlineKeyboard = new[] 
        {
            new[] { new InlineKeyboardButton(...), new InlineKeyboardButton(...) },
            new[] { new InlineKeyboardButton(...), new InlineKeyboardButton(...) },
        }
    }
}
```

**Comment by shdehnavi** [comment]
thanQ

what does this codes means ?

>             OneTimeKeyboard = true,
            ResizeKeyboard = true

**Comment by justdmitry** [comment]
All parameters are described in [Telegram documentation](https://core.telegram.org/bots/api#replykeyboardmarkup)
