### ISSUE TITLE
Как спарсить json от telegram

### ISSUE THREAD

**Issue by Radzhab** [justdmitry/NetTelegramBotApi#4]
Есть ли метод для парсинга готовый?

**Comment by Radzhab** [comment]
Я например не пользуюсь `GetUpdates`. Сделал webHook. На сервер приходит json. Как его сконвертировать в Update[]?

**Comment by justdmitry** [comment]
Я выделил десериализацию в отдельный метод - `DeserializeUpdate`, ветка `issue-4`.

Если я правильно понимаю документацию, в вебхук придет только один объект `Update` за раз, метод рассчитан на это и сможет десериализовать только один объект, не массив.

К сожалению у меня нет в оперативном доступе полноценного SSL-сертификата чтобы попробовать. Пожалуйста, сообщите что же все-таки возвращает сервер.

**Comment by Radzhab** [comment]
Только что проверил. В один момент времени приходит один массив Update) Вы правы. 

По поводу sll. Вот тут можно на три года зарегать https://www.wosign.com/english/

**Comment by Radzhab** [comment]
Все работает) метод DeserializeUpdate

**Comment by justdmitry** [comment]
Смерджил в мастера.
