### ISSUE TITLE
make ReplyMarkup keyboard with icons

### ISSUE THREAD

**Issue by shdehnavi** [justdmitry/NetTelegramBotApi#40]
hi
can i set icon for keyboard buttons like some bots ?

**Comment by justdmitry** [comment]
Keyboard Buttons displays [only text](https://core.telegram.org/bots/api#inlinekeyboardbutton), but you can use [unicode emoji](http://unicode.org/emoji/charts/full-emoji-list.html) (warning! heavy page!) as far as you believe your clients have them in their system fonts (i.e. have up-to-date OS): 🦋
