### ISSUE TITLE
bot stopped after a while

### ISSUE THREAD

**Issue by shdehnavi** [justdmitry/NetTelegramBotApi#42]
hi, im running my bots with NetTelegramBotApi on a windows server 2008 R2
my robot is disabled after a short time which it is inactive and doesnt receive any pm

what do i do ?

**Comment by justdmitry** [comment]
Add more logging and research what's going wrong. This library is only a helper for message/call formatting/parsing. 

My bot, created with NetTelegramBotApi and [NetTelegramBot.Framework](https://github.com/justdmitry/NetTelegramBot.Framework) is running without interrupts about two months.

**Comment by SHDN3T** [comment]
for example: after 5 min, my bot disabled and it doesnt make any action for received messages .

**Comment by SHDN3T** [comment]
for example: after 5 min my bot disabled and it doesnt make any action on received messages !

**Comment by shdehnavi** [comment]
for example: after 5 min my bot disabled and it doesnt make any action on received messages !

**Comment by justdmitry** [comment]
How you see your bot *received* message? What you mean *bot disabled*? How you know that? Sorry for my stupid questions, but I known nothing about your app.

**Comment by justdmitry** [comment]
No answer. Closing.
