### ISSUE TITLE
SendMessage doesn't work.

### ISSUE THREAD

**Issue by Ozymandy** [justdmitry/NetTelegramBotApi#45]
```
string API_HASH;
long user;
string message = "text";
TelegramBot bot = new TelegramBot(API_HASH);
try
{
    Console.WriteLine(
        bot.MakeRequestAsync(new NetTelegramBotApi.Requests.SendMessage(user, message))
             .GetAwaiter()
             .GetResult()
             .From
             .FirstName);
}
catch (Exception e)
{
    Console.WriteLine(e.Message);
    Console.Write(e.StackTrace);
    Console.Write(e.InnerException);
}
Console.ReadLine();
```
It's sample of code. No exception, anything. Just doesn't work.

**Comment by justdmitry** [comment]
I changed test project ([see branch `issue-45`](https://github.com/justdmitry/NetTelegramBotApi/blob/issue-45/TelegramBotDemo-vNext/Program.cs#L201-L207)) - your code works, my bot name is printed.

**Comment by Ozymandy** [comment]
@justdmitry 
![50f90c9005b9129623c38020e4991eea7c1997a5360edb8ed7 pimgpsh_fullsize_distr](https://cloud.githubusercontent.com/assets/3194888/23142111/c9b054e6-f7ec-11e6-89c3-18a2cfebd2d8.png)
I tested on one pc, and it works there, but I had this.

**Comment by justdmitry** [comment]
"Невозможно соединиться с удаленным сервером" это уже явно проблемы на сетевом уровне. Что-то мешает соединиться с сервером Telegram.

Проект `TelegramBotDemo-vNext` работает (в `config.json` надо указать валидный токен)? Надо искать проблему (в самой винде) пока не заработает.

**Comment by Ozymandy** [comment]
@justdmitry  да. Ломаю голову в чём дело. Некорректно работал telegram api(не бот) и было проблема в несинхронизированном времени на компьютере. Но тут это не помогло.
