### ISSUE TITLE
Triggering messages

### ISSUE THREAD

**Issue by dnogueir** [justdmitry/NetTelegramBotApi#47]
Hi, I've just updated an old application using NetTelegramBotApi, and I would like to trigger a message to every user of my bot informing them about the changes and new functionalities. Is there a way I can do that without the need of expecting the user to start a conversation ?

thanks!

**Comment by justdmitry** [comment]
You should load list of `chat_id`'s of your users from some "database" where you should been saved them before. Nobody knows list of your users except you.

**Comment by dnogueir** [comment]
Thanks for replying, I am new to bots, started working on a running project, and didnt realize we had a list of chat_id's in the database. It just worked, thank you.
