### ISSUE TITLE
inline mode for game

### ISSUE THREAD

**Issue by ghost** [justdmitry/NetTelegramBotApi#49]
I think NetTelegramBotApi
does not have InlineQueryResultGame, if it has please help to create inline keyboard for games, this is not a bug exactly, but i think its an issue

thanks...

**Comment by justdmitry** [comment]
Inline mode requires a lot of classes to be created.

I added some of them [in `inline` branch](https://github.com/justdmitry/NetTelegramBotApi/commits/inline) - you may copy this classes to your solution and use.

Also, feel free to make PR for other classes.
