### ISSUE TITLE
UTF8 file name error

### ISSUE THREAD

**Issue by farazp** [justdmitry/NetTelegramBotApi#5]
hi when I want to send file with UTF8 filename, don't show correct file name,
for example my file name is فارسی.docx but at reception user show filename like: =?utf-8?B?RDpcVXNlcnNcQXBhY2hpXERvY3VtZW50c1zYrdmF2K8g2YXYutix2KjZii5kb2N4?=

**Comment by justdmitry** [comment]
It looks that Telegram servers do not understand 'extended' `filename*` param in header value and expect utf-8 string in regular `filename`...

Fixing this seems like a hack, but I have no choice.
