### ISSUE TITLE
problem of  [400] Bad Request: REPLY_MARKUP_GAME_EMPTY

### ISSUE THREAD

**Issue by ghost** [justdmitry/NetTelegramBotApi#50]
Hi, what the problem?
![untitled2](https://cloud.githubusercontent.com/assets/22222498/25525836/16624f70-2c26-11e7-94d4-199c08cea97c.jpg)
![Uploading Untitled4.jpg…]()

and even i remove the callbackgame and callback data gave me these error of empty markup,

**Comment by justdmitry** [comment]
Duplicate of #51

**Comment by justdmitry** [comment]
Please show your code, I never worked with Telegram games.

**Comment by justdmitry** [comment]
Duplicate of #50
