### ISSUE TITLE
Using NetTelegramBotAPI in Visual Studio for Mac

### ISSUE THREAD

**Issue by manili** [justdmitry/NetTelegramBotApi#56]
Is it possible to clone NetTelegramBotAPI project and run it on VS for Mac?
Because I can't compile it and get this error:
Can not find System.NET.Http are you missing an assembly?

Thanks

**Comment by justdmitry** [comment]
Never tried.

May be that's because project set to cross-compile for `net45`, `net46`, and `netstandard1.3` - obviously you don't have `net45` and `net46` on Mac. Remove extra frameworks from project file manually.

**Comment by manili** [comment]
Thanks for reply.
I made a new project and tried to add NetTelegramBotAPI files manually. I've done the job successfully however it was a little tricky.
It would be my pleasure to share my experience with the others if you wish (adding instructions to wiki, upload the whole project or etc ...)?

**Comment by justdmitry** [comment]
Best document is code itself. Fork this project and commit Mac (VSCode?) -compatible project file(s). Even if it can't be merged without breaking Windows/VS dev experience - anyone who face same problem can easily obtain your code and start working.
