### ISSUE TITLE
AnswerInlineQuery in NetTelegramBotApi

### ISSUE THREAD

**Issue by rasools13** [justdmitry/NetTelegramBotApi#58]
I use NetTelegramBotApi to creat my bot, but I cann't find AnswerInlineQuery method to handle inlineQuery?

**Comment by justdmitry** [comment]
Inline mode is not complete - you may create required classes yourself using one of existing as a sample.

**Comment by rasools13** [comment]
hi again @justdmitry  
I created all necessary classes for AnswerInlineQuery (see the attachment files) and everything looks good, but I encounter "Invalid Inline_Query_Id" error when using that.
```
InlineQueryResult inline_result = new InlineQueryResult();
InputTextMessageContent txtmesg = new InputTextMessageContent();
txtmesg.MessageText = "this is inline nessage content";
inline_result.InputMessageContent = txtmesg;
inline_result.Title = "inline title";
                                                                           
await bot.MakeRequestAsync(new AnswerInlineQuery(UpD.InlineQuery.Id, inline_result));
```
[Requests.zip](https://github.com/justdmitry/NetTelegramBotApi/files/1295928/Requests.zip)

**Comment by justdmitry** [comment]
It's hard to say where the problem is looking into archive. I see "strange" property names, possibly conflicting with JSON serializer settings... Can you make a PR or commit changes to branch in [your fork](https://github.com/rasools13/NetTelegramBotApi/)?
