### ISSUE TITLE
Send pdf

### ISSUE THREAD

**Issue by hanigamini** [justdmitry/NetTelegramBotApi#6]
Hi,
when i want send pdf file this error accourd 
Value cannot be null.
Parameter name: content

using (var docData = Assembly.GetExecutingAssembly().GetManifestResourceStream("TelegramBotDemo.test.pdf"))
                                {

```
                                var req = new SendDocument(update.Message.Chat.Id, new FileToSend(docData, "test.pdf"));
                                var msg = bot.MakeRequestAsync(req).Result;
                                uploadedDocumentId = msg.Document.FileId;
                            }
```

**Comment by justdmitry** [comment]
If I understand correctly, you added a new file to `TelegramBotDemo` project.
Please check that:
- you added file to root of project, not subfolder
- you set in properties for that file `Build action = Embedded resource` (like two other sample files)

Anyway, `docData` is a simple `System.IO.Stream` and you can use any source for it - like `System.IO.File.OpenRead` or `MemoryStream` - it's up to you.

**Comment by hanigamini** [comment]
Hi,
Thanks for your response.
