### ISSUE TITLE
Dynamic Inline keyboards

### ISSUE THREAD

**Issue by hanigamini** [justdmitry/NetTelegramBotApi#61]
Hello,
I want read text and CallbackData (ID) of inline keyboard from for loop (from database) and then show to user,how do it ?

InlineKeyboardButton inlineKeyboardButton;
                            for (int i = 0; i < 5; i++)
                            {
                                inlineKeyboardButton = new InlineKeyboardButton { Text = "test" + i, CallbackData = "callback" + i };
....
                            }
....
var keyb = new InlineKeyboardMarkup()
                            {
                                InlineKeyboard = new[] { new[] { inlineKeyboardButton, inlineKeyboardButton2,.... }, new[] { inlineKeyboardButton3 } }
                            };

**Comment by justdmitry** [comment]
Your code seems ok. What exact problem you have?

**Comment by hanigamini** [comment]
I found it , i want dynamic keyboard , but this is one line button , i want each line have only 2 button,
Do you have any solution?

private static InlineKeyboardButton[][] GetInlineKeyboard(string[] stringArray)
        {
            var keyboardInline = new InlineKeyboardButton[1][];
            var keyboardButtons = new InlineKeyboardButton[stringArray.Length];
            for (var i = 0; i < stringArray.Length; i++)
            {
                keyboardButtons[i] = new InlineKeyboardButton
                {
                    Text = stringArray[i],
                    CallbackData = "Some Callback Data",
                };
            }
            keyboardInline[0] = keyboardButtons;
            return keyboardInline;
        }
....
 var buttonItem = new[] { "one", "two", "three", "Four", "Four", "Four", "Four", "Four", "Four", "Four", "Four", "Four", "Four" };
                            var keyb = new InlineKeyboardMarkup()
                            {
                                InlineKeyboard = GetInlineKeyboard(buttonItem)

                            };

**Comment by justdmitry** [comment]
You should put two `InlineKeyboardButton` into one inner array. You should got hierarchy like this (of course this must be `InlineKeyboardButton`s):

    [
        [ "one", "two"],
        [ " three", "four" ],
        ...
    ]

**Comment by hanigamini** [comment]
Hi,
Thansk for your response ,
I Found it , I mean, this

private static InlineKeyboardButton[][] GetInlineKeyboard()
        {            
            DataTable dt = .....
            int keyboardRows = 0;
            if (dt.Rows.Count % 2 == 0)
            {
                keyboardRows = dt.Rows.Count / 2;
            }
            else
            {
                keyboardRows = (dt.Rows.Count / 2) + 1;
            }

            var keyboardInline = new InlineKeyboardButton[keyboardRows][];
            var keyboardButtons = new InlineKeyboardButton[dt.Rows.Count];
            for (var i = 0; i < dt.Rows.Count; i++)
            {
                keyboardButtons[i] = new InlineKeyboardButton
                {
                    Text = dt.Rows[i]["Name"].ToString(),
                    CallbackData = dt.Rows[i]["id"].ToString(),
                };
            }
            for (int r = 0, s = 0; r < keyboardRows; r++, s++)
            {
                if (dt.Rows.Count % 2 == 0)
                {
                    keyboardInline[r] = new InlineKeyboardButton[] { keyboardButtons[r + s], keyboardButtons[r + s + 1] };
                }
                else
                {
                    if ((r + s) != keyboardButtons.Length - 1)
                    {
                        keyboardInline[r] = new InlineKeyboardButton[] { keyboardButtons[r + s], keyboardButtons[r + s + 1] };
                    }
                    else
                    {
                        keyboardInline[r] = new InlineKeyboardButton[] { keyboardButtons[r + s] };
                    }
                }
            }
           
            return keyboardInline;
        }

**Comment by justdmitry** [comment]
Great!
