### ISSUE TITLE
Delete Message from group

### ISSUE THREAD

**Issue by hanigamini** [justdmitry/NetTelegramBotApi#63]
Hi , 
I want read message from supergroup , check this and delete if condition true.
if (update.Message.Chat.Type == "supergroup")
                        {
......
}

**Comment by justdmitry** [comment]
You need [deleteMessage](https://core.telegram.org/bots/api#deletemessage) request. It's not implemented in current version, but you may easily add it yourself:

    using System;
    using System.Collections.Generic;
    using System.Globalization;
    using System.Net.Http;
    using NetTelegramBotApi.Types;

    namespace NetTelegramBotApi.Requests
    {
        public class DeleteMessage : RequestBase<bool>
        {
            public DeleteMessage(long chatId, long messageId)
                : base("deleteMessage")
            {
                this.ChatId = chatId;
                this.MessageId = messageId;
            }
            public DeleteMessage(string channelName, long messageId)
                : base("deleteMessage")
            {
                this.ChannelName = channelName;
                this.MessageId = messageId;
            }

            public long? ChatId { get; protected set; }
            public string ChannelName { get; set; }
            public long MessageId { get; protected set; }

            public override HttpContent CreateHttpContent()
            {
                if (ChatId.HasValue && !string.IsNullOrEmpty(ChannelName))
                {
                    throw new Exception("Use ChatId or ChannelName, not both.");
                }
                
                var dic = new Dictionary<string, string>();

                if (ChatId.HasValue)
                {
                    dic.Add("chat_id", ChatId.Value.ToString(CultureInfo.InvariantCulture));
                }
                
                if (!string.IsNullOrEmpty(ChannelName))
                {
                    dic.Add("chat_id", ChannelName);
                }

                dic.Add("message_id", MessageId.ToString(CultureInfo.InvariantCulture));

                return new FormUrlEncodedContent(dic);
            }
        }
    }

(written in notepad, so typos are possible)

**Comment by hanigamini** [comment]
I wrote this but error (Could not cast or convert from System.Boolean to NetTelegramBotApi.Types.Message.) in  var result = DeserializeMessage<BotResponse<T>>(responseText); line in MakeRequestAsync<T> method

But it ok with your code !!! I had forgotten return bool.

Thanks.

public class DeleteMessage : RequestBase<Message>
    {
        public DeleteMessage(long chatId, long message_id)
            : base("deleteMessage")
        {
            this.ChatId = chatId;
            this.message_id = message_id;
        }

        public long? ChatId { get; set; }

        public long message_id { get; set; }

        public override HttpContent CreateHttpContent()
        {
            //if (ChatId.HasValue)
            //{
            //    throw new Exception("Use ChatId, not both.");
            //}
            var dic = new Dictionary<string, string>();

            if (ChatId.HasValue)
            {
                dic.Add("chat_id", ChatId.Value.ToString(CultureInfo.InvariantCulture));
            }
           
            dic.Add("message_id", message_id.ToString(CultureInfo.InvariantCulture));
          

            return new FormUrlEncodedContent(dic);
        }
    }
