### ISSUE TITLE
 Left from group when add

### ISSUE THREAD

**Issue by hanigamini** [justdmitry/NetTelegramBotApi#64]
Hi,
How can I  Left from group when some one add my bot to group ?

**Comment by justdmitry** [comment]
I don't see any requests like self-kicking in Telegram bot api. May be https://core.telegram.org/bots/api#kickchatmember may help, but your bot must be admin in chat.

**Comment by hanigamini** [comment]
I want prevent unwanted add my bot in group ,
I want left form that group.
this is method , leaveChat , how can i use it?
https://core.telegram.org/bots/api#leavechat

**Comment by justdmitry** [comment]
I can't find something in [Telegram bot API docs](https://core.telegram.org/bots/api) that may help you.

Any bot may be added in any chat. You may start replying on every message in chat with some spam and humans will remove your bot very quickly ;)

**Comment by hanigamini** [comment]
leaveChat , how can i use it?
https://core.telegram.org/bots/api#leavechat

**Comment by justdmitry** [comment]
Wow, my eyes. You are right, that's exactly what you need.

So, just send 'LeaveChat`:

    var chatToLeave = message.Chat.Id;
    await bot.SendAsync(chatToLeave, new LeaveChat(chatToLeave));

**Comment by hanigamini** [comment]
your code not work , whast is the diffrence with this ?
bot.MakeRequestAsync(new LeaveChat(chatToLeave)).Wait();

**Comment by justdmitry** [comment]
Ouch, sorry. 

I'm not with VS now, writing in "notepad". My code is from [NetTelegramBot.Framework](https://github.com/justdmitry/NetTelegramBot.Framework), it will not compile in "naked" NetTelegramBotApi.

Your code is correct one and should work.

**Comment by hanigamini** [comment]
Thank you very much, 
I add try cacth in c# because somtime have error with LeaveChat. and bot is in hanging.
Is there any way for that ?
