### ISSUE TITLE
User in group

### ISSUE THREAD

**Issue by hanigamini** [justdmitry/NetTelegramBotApi#66]
Hi,
How can i understand user that send message in group , How many people added to this group by this user?

**Comment by justdmitry** [comment]
If you can find any bot API request in https://core.telegram.org/bots/api about your task - you may use that request. Otherwise - you should analyze all incoming updates and save `new_chat_members` somewhere in you database.

**Comment by hanigamini** [comment]
Hi,
Thanks ,
I save in my database and analyze it.
