### ISSUE TITLE
Bot Messages

### ISSUE THREAD

**Issue by hanigamini** [justdmitry/NetTelegramBotApi#68]
Hi,
The message that robot send to group is not Traceable.
The message not seen in get update .
I want delete all message that send by robot in group.

**Comment by justdmitry** [comment]
From [sendMessage](https://core.telegram.org/bots/api#sendmessage): On success, the sent Message is returned.

You should analyze response and save message_id in your database.

**Comment by hanigamini** [comment]
Hi,
Thanks , 
I did the same
