### ISSUE TITLE
Know that user join a channel

### ISSUE THREAD

**Issue by itarfand** [justdmitry/NetTelegramBotApi#71]
Hi. How do I check that a user joined a channel with this library?

**Comment by justdmitry** [comment]
Message.NewChatMember ?

**Comment by itarfand** [comment]
thank you. How do I check every time that user is a member of other channel like @channel whit this method?

**Comment by justdmitry** [comment]
You can't check if user is member of some other channel. You must be admin of that "other" channel and know list of it members somewhere in your database.

**Comment by itarfand** [comment]
The bot and me are admin on that channel
In telegram API we have these method:

                        string channel = "@channelname";
                        long id = item.Message.Chat.Id;
                        GetChatMember checkUser = new GetChatMember(channel, id);                        
                        ChatMember whatUserInChannel = new ChatMember();

How can I check with this method that user join a channel?

**Comment by justdmitry** [comment]
Send `GetChatMember` request to Telegram:

`var chatMember = await mybot.SendAsync(checkUser)`

See also: [docs for GetChatMember](https://core.telegram.org/bots/api#getchatmember)

**Comment by ReverseSun** [comment]
Hi
I have this problem with conditions and its really bothering...
I search whole github for using these in "if" and I found nothing useful..
how should I put this into if or else?
I mean check if id is one of the channel member..
Can you guys help me with that? plz.. tnx
