### ISSUE TITLE
MTProto Proxies

### ISSUE THREAD

**Issue by MTare** [justdmitry/NetTelegramBotApi#74]
How to use MTProto Proxies in my bot?

**Comment by justdmitry** [comment]
How exactly you want to use proxies in [bot API](https://core.telegram.org/bots/api)? Can't find any proxy-related objects/messages

**Comment by MTare** [comment]
I want to set specific properties in my bot to use MTPro Proxies,
You can see these properties in the attachment.

**Comment by justdmitry** [comment]
Attachments are not copied to GitHub, write them "in text" please

**Comment by MTare** [comment]
MTProto Proxies have these Properties:
Server,port,secret key

**Comment by justdmitry** [comment]
:(

Re-read [Bot API](https://core.telegram.org/bots/api). It does not use proxies in any way.

**Comment by Ezergil** [comment]
@justdmitry sup
As you well aware - telegram is restricted in some countries, e.g. Russia, so direct requests to api.telegram are not possible
Using proxy could solve this issue, it is possible to pass proxy to HttpClient constructor
I know how to pass http and Socks proxies there, but what with MTProto?

**Comment by justdmitry** [comment]
@Ezergil MTProto is not used for bot API, only for "native" Telegram communications. You need http(s) proxy. Use `TelegramBot.WebProxy` or override `TelegramBot.MakeHttpMessageHandler` to add your proxy info.
