### ISSUE TITLE
TLS 1.2 issue

### ISSUE THREAD

**Issue by rogercorrea** [justdmitry/NetTelegramBotApi#76]
Please,

Does the library support TLS 1.2?
I updated my server (Windows 2008 R2) and inserted line to default TLS 1.2 in .NET Framework 4.5, but don't work for me.

`ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12;`

Error description:
The request was canceled: A secure channel for SSL / TLS could not be created

**Comment by justdmitry** [comment]
Library uses "standard" HttpClient and does not make any configurations for SSl/TLS or other.

If your Windows/.NETFramework installation can connect with TLS2 using HttpClient - library will connect too.

**Comment by rogercorrea** [comment]
I installed kb to transform TLS 1.2 to default but don't worked for me in Windows 2008 R2 using the library NetTelegram.

https://support.microsoft.com/en-us/help/3140245/update-to-enable-tls-1-1-and-tls-1-2-as-default-secure-protocols-in-wi

**Comment by justdmitry** [comment]
Try using HttpClient directly. Library use it and does not have any additional configuration.

**Comment by rogercorrea** [comment]
I changed OS to Windows 2016 and solved my problem.
Windows 2008 R2 don't work fine with TLS 1.2.
